### ISSUE TITLE
Should calling `dipose()` on an already disposed `DisposeScope` throw?

### ISSUE THREAD

**Issue by bartekpacia** [RobertOdrowaz/dispose-scope#31]
I'm kind of leaning towards thinking that it should be simply a no-op.

FWIW, there's [`package context`](https://pkg.go.dev/context) in Go, which serves a roughly similar purpose, and allows for calling `Cancel()` many times (all subsequent calls are no-ops).

cc @RobertOdrowaz

**Comment by shilangyu** [comment]
I'd say calling dipose twice is an indication of a bug. 

Cancellation is a different usecase, where calling cancel multiple times does make sense. Take for instance `StreamSubscription`. You can cancel it as many times you want. This is ok, since there might be many sources of cancellation. But disposal should be equivalent to "i have this object and I will no longer use it". If you use it after disposing (use-after-free) it should be a bug. Similarly if you dispose it twice (double-free) it is an indication that someone was holding your object which you promised won't be used anymore.

**Comment by bartekpacia** [comment]
This makes perfect sense. Thanks and I agree the current behavior of `dispose_scope` is OK.
